### ISSUE TITLE
Suggested improvement #4: Add a pause option

### ISSUE THREAD

**Issue by FixItDik** [michaelbutler/minesweeper#10]
It would be really nice to add a button which pauses the timer so you can answer a call (of nature or phone) in the middle of a game.  On the Windows version this happened if you minimised the game but for this version I think a button will do.  However it also needs to prevent them "cheating" by using the pause to give themselves time to think, so the board should be hidden while the timer is paused.

**Comment by michaelbutler** [comment]
Resolved in https://github.com/michaelbutler/minesweeper/pull/12 and merged in https://github.com/michaelbutler/minesweeper/pull/18
