### ISSUE TITLE
Mines are not generated after first click

### ISSUE THREAD

**Issue by ryzizub** [michaelbutler/minesweeper#15]
Mines have to be generated after the first click. User cant experience losing the game in the first click.

**Comment by michaelbutler** [comment]
well that's minesweeper. You don't know where the mines are! Isn't it not guaranteed to be winnable?

**Comment by ryzizub** [comment]
:smile: yea it's not guaranteed. But loosing after the first click in minesweeper is I think bad. You have to be able to click even once. Mines should be generated at that click. That's how for example old minesweeper on MS works

**Comment by michaelbutler** [comment]
Thanks, Fixed in https://github.com/michaelbutler/minesweeper/pull/17
