### ISSUE TITLE
You should create a gh-pages branch

### ISSUE THREAD

**Issue by thebugjim** [michaelbutler/minesweeper#3]
Look into gh-pages, I and a lot of people would probably love to try out your game, but it's a little inconvient to have to clone it. May as well just host on gh-pages for free!

**Comment by michaelbutler** [comment]
Yes, you're right. I should get around to hosting it. Thanks for the suggestion!

**Comment by michaelbutler** [comment]
@thebugjim I added a github pages entry for this project so you can actually play the game at http://michaelbutler.github.io/minesweeper/ -- Do you know how I can keep the github pages branch in sync with the master branch so I do not have to change the files in both branches? Should I just merge gh-pages to master and make that the one branch I use going forward?

**Comment by thebugjim** [comment]
I usually just keep committing to master, then push master onto gh-pages when I'm ready. Idk if there's a better way, but it's not that bad.

     git add -am 'hi'
     git push origin master
     git push origin master:gh-pages

**Comment by michaelbutler** [comment]
Done at http://michaelbutler.github.io/minesweeper/
