### ISSUE TITLE
Suggested improvement #2: Implement Shift & Ctrl key modifier to mouse clicks

### ISSUE THREAD

**Issue by FixItDik** [michaelbutler/minesweeper#7]
Suggested improvement: Allow the use of the shift or ctrl key to make a left button on the mouse behave as the right button (as in the Windows version)

The "click both buttons at once" works well enough, but if you were used to the shift or ctrl key feature in the Windows version it does feel slightly easier

**Comment by michaelbutler** [comment]
You fixed this I believe. And also this feature made it much faster to play on a mac book, which does not have a right mouse button!
